/* Autogenerated by png2wx.pl on Sat Mar 28 19:18:21 2020 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_meteovache_pi;
extern wxBitmap *_img_meteovache_tb;

#endif /* ICONS_H */
